[package]
name = "fibonacci_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fibonacci_lib={path = "../fibonacci_lib"}